# Generated by Django 5.0.6 on 2024-05-31 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_room_name_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="room",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.room"
            ),
        ),
    ]
