# Generated by Django 5.0.6 on 2024-05-31 21:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_user_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(
                default=api.models.generate_random_name, max_length=50, null=True
            ),
        ),
    ]
