# Generated by Django 5.0.6 on 2024-06-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_user_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="room",
        ),
        migrations.AddField(
            model_name="user",
            name="room_code",
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
