# Generated by Django 5.0.6 on 2024-06-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_user_room_user_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="room_code",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
